### ISSUE TITLE
Looping History with Unicode Items

### ISSUE THREAD

**Issue by mitnk** [murarth/linefeed#7] opened 2017-04-03 04:05 UTC
When adding history and fetch them back with `Ctrl+P`, Unicode item would result wrong buffer rendering.

```
demo $ echo hi
hi
demo $ ls 世界
ls: 世界: No such file or directory
demo $ echo yoo
yoo
```
Then, let's fetch items back with `Ctrl+P`:
```
demo $ echo yoo       # <-- first `Ctrl+P` got "echo yoo", good!
demo $ ls 世界      # <-- second, we got "ls 世界", good!
demo $ lsecho hi    # <-- now a third `Ctrl+P` fetched something weird
```
Though, when you hit ENTER now, you will get output "hi", which means this is only a rendering issue. It is actually "echo hi" in buffer, not "lsecho hi".

**Comment by murarth** [comment] 2017-04-03 05:39
Yes, there appears to be a mistake in how multibyte characters are counted. I'm looking into it now.

**Comment by murarth** [comment] 2017-04-03 06:15
Nope. I was mistaken. Multibyte characters are handled properly as far as moving the internal cursor around.

The issue is actually caused by [fullwidth characters](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms) and how they are treated by terminals. Solving this problem will be a bit more interesting. Fortunately, there already exists a crate for computing the width of a string, so the most confusing part is already done.

**Comment by mitnk** [comment] 2017-04-03 06:36
Linefeed seems know the total chars (i.e. 5 for "ls 世界") in buffer. But when moving cursor, it seems cursor moves over bytes (two moves on surface of char "界") instead of chars (or [boundary](https://doc.rust-lang.org/std/primitive.str.html#method.is_char_boundary)), compare to bash.

**Comment by murarth** [comment] 2017-04-03 07:45
That was my first thought, as well, but it turned out to be wrong. Other multibyte characters such as "ü" and "•" were being treated correctly.

What's actually happening is that the terminal application considers characters such as "世" (called fullwidth characters) to be occupying two columns. `linefeed` was erroneously assuming that any character could occupy only one column and so, when it would signal to the terminal to move from the end of the line to the beginning of the line "ls 世界", it would signal to the terminal to move five columns left. Instead, `linefeed` must signal to the terminal to move seven columns left.

I've corrected by this checking for fullwidth characters (using the simple and wonderful [`unicode-width`](https://crates.io/crates/unicode-width) crate) and giving such characters two columns, which implicitly corrects terminal cursor movement operations.

I've just committed this change. Please let me know if it solves the problem or if you encounter any other issues.

**Comment by mitnk** [comment] 2017-04-03 07:54
Just checked with master, it solved the issue! Awesome! Thanks a lot!

**Closed as completed** 2017-04-03 20:43 UTC

**Comment by murarth** [comment] 2017-04-03 20:48
You're welcome and thanks for filing the issue. Also, I've just published the fix on crates.io as version `0.2.3`.
