### ISSUE TITLE
Command 'Transpose words' does not work as expected

### ISSUE THREAD

**Issue by gwenn** [murarth/linefeed#17] opened 2017-09-17 08:48 UTC
a) Launch the demo
b) Input `ßeta / δelta__`
c) Press `Meta-T`
Expected `δelta__ / ßeta`, got `ßeta δelta__ /`

**Comment by murarth** [comment] 2017-09-17 17:14
It appears the readline command behaves as you expect, as well. I was not aware that readline looked for non-symbol words when transposing. I'll work on a fix for this.

**Comment by murarth** [comment] 2017-09-17 20:16
Correction: This is not a bug. It's simply that the default set of word break characters (indicated [here](https://cnswww.cns.cwru.edu/php/chet/readline/readline.html#IDX385) in GNU Readline documentation) does not include `/` and therefore considers `/` to be a word. If one inputs `ßeta | δelta__` instead (`|` being within the default set of word break characters), the behavior is as expected.

**Closed as completed by murarth** 2017-09-17 20:16 UTC
